//! macOS login-item registration for the background agent service.
//!
//! The GUI owns this side of the agent's lifecycle: `SMAppService` resolves
//! its plist against the *calling* app's bundle
//! (`Contents/Library/LaunchAgents/<label>.plist`, generated by
//! `xtask`), so only this process can register it. Registration is what puts
//! launchd in charge — start at login, respawn after a crash
//! (`KeepAlive = {SuccessfulExit: false}`), a visible row under System
//! Settings › Login Items — and the `launch_at_login` setting maps onto
//! register/unregister here. The agent's own `launch_agent` module keeps only
//! the migration away from the legacy hand-written plists.
//!
//! Everything is a no-op off macOS (the agent reconciles its autostart there)
//! and reports [`ServiceStatus::Unsupported`].

/// Where the agent service stands with launchd, mirroring
/// `SMAppServiceStatus` plus a cross-platform "not this platform" arm.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ServiceStatus {
    /// Registered and eligible to run — `launchctl kickstart` can start it.
    Enabled,
    /// Registered, but the user switched it off in System Settings › Login
    /// Items; nothing can start it until they switch it back on.
    RequiresApproval,
    /// Not registered (never, or unregistered since).
    NotRegistered,
    /// The framework could not find the service at all — typically a bundle
    /// without the embedded plist (a bare dev binary).
    NotFound,
    /// Not macOS.
    Unsupported,
}

/// The launchd service label this process manages: the dev variant inside a
/// dev-profile bundle, so a dev registration can never collide with the
/// shipped one.
#[must_use]
pub fn agent_service_label() -> String {
    if openlogi_core::paths::is_dev_profile() {
        openlogi_core::brand::dev_id(openlogi_core::brand::AGENT_SERVICE_LABEL)
    } else {
        openlogi_core::brand::AGENT_SERVICE_LABEL.to_owned()
    }
}

/// Current registration status of the agent service.
#[must_use]
#[cfg_attr(
    target_os = "macos",
    expect(unsafe_code, reason = "plain ObjC property read via objc2 bindings")
)]
pub fn status() -> ServiceStatus {
    #[cfg(target_os = "macos")]
    {
        use objc2_service_management::SMAppServiceStatus;
        // SAFETY: plain ObjC property read on a service handle this process
        // owns; no pointers cross the boundary.
        let status = unsafe { macos::service().status() };
        match status {
            SMAppServiceStatus::Enabled => ServiceStatus::Enabled,
            SMAppServiceStatus::RequiresApproval => ServiceStatus::RequiresApproval,
            SMAppServiceStatus::NotFound => ServiceStatus::NotFound,
            // NotRegistered, and any future framework value: nothing is
            // registered that we could rely on.
            _ => ServiceStatus::NotRegistered,
        }
    }
    #[cfg(not(target_os = "macos"))]
    ServiceStatus::Unsupported
}

/// Reconcile the registration with the `launch_at_login` setting: register
/// when `enabled` (idempotent — an existing registration is success),
/// unregister otherwise (an absent one likewise). Registering starts the
/// service immediately; unregistering stops a running one, which the IPC
/// client's spawn retry then restarts unmanaged — a brief blip, and the
/// honest one: the alternative is a login item the user just disabled still
/// governing the process.
///
/// # Errors
///
/// The framework's error description — an unsigned bundle, a missing embedded
/// plist (bare dev binary), or launchd refusing the operation.
pub fn sync_registration(enabled: bool) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    {
        macos::sync_registration(enabled)
    }
    #[cfg(not(target_os = "macos"))]
    {
        let _ = enabled;
        Ok(())
    }
}

/// Open System Settings on the Login Items pane — where the user re-enables a
/// service whose status is [`ServiceStatus::RequiresApproval`].
#[cfg_attr(
    target_os = "macos",
    expect(
        unsafe_code,
        reason = "plain no-argument ObjC class method via objc2 bindings"
    )
)]
pub fn open_login_items_settings() {
    #[cfg(target_os = "macos")]
    // SAFETY: plain ObjC class method with no arguments.
    unsafe {
        objc2_service_management::SMAppService::openSystemSettingsLoginItems();
    }
}

#[cfg(target_os = "macos")]
mod macos {
    use objc2::rc::Retained;
    use objc2_foundation::{NSError, NSString};
    use objc2_service_management::SMAppService;

    use super::agent_service_label;

    /// The framework handle for the agent service's embedded plist.
    #[expect(unsafe_code, reason = "plain ObjC class method via objc2 bindings")]
    pub(super) fn service() -> Retained<SMAppService> {
        let plist_name = NSString::from_str(&format!("{}.plist", agent_service_label()));
        // SAFETY: plain ObjC class method; the name is a valid NSString.
        unsafe { SMAppService::agentServiceWithPlistName(&plist_name) }
    }

    #[expect(unsafe_code, reason = "plain ObjC calls via objc2 bindings")]
    pub(super) fn sync_registration(enabled: bool) -> Result<(), String> {
        let service = service();
        // SAFETY: plain ObjC calls on a handle this process owns; the
        // returned NSError is a `Retained` the binding manages.
        let result = unsafe {
            if enabled {
                service.registerAndReturnError()
            } else {
                service.unregisterAndReturnError()
            }
        };
        result.or_else(|error| {
            if already_converged(&error, enabled) {
                Ok(())
            } else {
                Err(error.localizedDescription().to_string())
            }
        })
    }

    /// Whether `error` only says the service is already in the desired state:
    /// registering an already-registered service, or unregistering an absent
    /// one. Matched by the framework's own error constants, never bare ints.
    #[expect(
        unsafe_code,
        reason = "reading a framework-provided immutable static NSString"
    )]
    fn already_converged(error: &NSError, enabled: bool) -> bool {
        use objc2_service_management::{kSMErrorAlreadyRegistered, kSMErrorJobNotFound};

        // SAFETY: the extern static is an immutable framework-owned NSString.
        let domain_matches =
            &*error.domain() == unsafe { objc2_service_management::SMAppServiceErrorDomain };
        let benign = if enabled {
            kSMErrorAlreadyRegistered
        } else {
            kSMErrorJobNotFound
        };
        domain_matches && isize::try_from(benign).is_ok_and(|code| error.code() == code)
    }
}
