//! Registration of the background agent's launchd service (macOS).
//!
//! The GUI owns this side of the agent's lifecycle: `SMAppService` resolves
//! plists against the *calling* app's bundle
//! (`Contents/Library/LaunchAgents/<label>.plist`, generated by `xtask`), so
//! only this process can register it. There is exactly **one** service, and
//! registration is deliberately **not** coupled to the `launch_at_login`
//! preference: launchd's model is a set of triggers on one job, so the
//! service plist always carries the login trigger and supervision
//! (`KeepAlive = {SuccessfulExit: false}`), while the preference is a plain
//! config value the *agent* reads when it starts — preference off, no client
//! demand, and the agent idles out on its own (the sunk-switch model). That
//! keeps registration a register-once affair: the toggle never touches
//! `SMAppService`, never re-prompts the user, and has no half-switched
//! failure states.
//!
//! What this module does do:
//!
//! - [`ensure_registered`]: converge toward "the service is registered",
//!   driven by a pure convergence rule (which carries the tests). A version
//!   marker under the data dir triggers the re-registration Apple requires
//!   after the executable changes (an app update).
//! - Respect the user's master switch: a service switched off under System
//!   Settings › Login Items ([`ServiceStatus::RequiresApproval`]) blocks
//!   every launch path, and is never re-registered — not even by the update
//!   path; the settings window surfaces it instead.
//!
//! One module per OS: `macos` owns every `SMAppService` call; everywhere
//! else `unsupported` is a no-op that reports
//! [`ServiceStatus::Unsupported`] (the agent reconciles its own autostart
//! there).

#[cfg(target_os = "macos")]
mod macos;
#[cfg(not(target_os = "macos"))]
mod unsupported;

#[cfg(target_os = "macos")]
use macos as platform;
#[cfg(not(target_os = "macos"))]
use unsupported as platform;

#[cfg(target_os = "macos")]
pub use macos::agent_service_label;

/// Where the agent service stands with launchd, mirroring
/// `SMAppServiceStatus` plus a cross-platform "not this platform" arm.
///
/// Off macOS only [`Self::Unsupported`] is ever constructed, but the macOS
/// variants stay: cross-platform consumers name them (the settings window
/// compares [`Self::RequiresApproval`] on every platform). Not `expect`: the
/// dead-code lint fires only on the non-macOS lanes, so an expectation would
/// go unfulfilled on macOS.
#[cfg_attr(
    not(target_os = "macos"),
    expect(clippy::allow_attributes, reason = "see above")
)]
#[cfg_attr(
    not(target_os = "macos"),
    allow(dead_code, reason = "only Unsupported is constructed off macOS")
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ServiceStatus {
    /// Registered and eligible to run — `launchctl kickstart` can start it.
    Enabled,
    /// Registered, but the user switched it off in System Settings › Login
    /// Items — the master switch: it blocks the login start, kickstart, and
    /// crash respawn alike until they switch it back on.
    RequiresApproval,
    /// Not registered (never, or unregistered since).
    NotRegistered,
    /// The framework could not find the service at all — typically a bundle
    /// without the embedded plist (a bare dev binary).
    NotFound,
    /// Not macOS. The variant only exists where it is constructed, so the
    /// macOS build carries no dead arm.
    #[cfg(not(target_os = "macos"))]
    Unsupported,
}

/// Current registration status of the agent service.
#[must_use]
pub fn status() -> ServiceStatus {
    platform::status()
}

/// Converge toward "the agent service is registered": status read, the pure
/// convergence rule, then the framework calls, then the version marker.
/// Self-contained — safe to run entirely on a background thread, and
/// deliberately independent of `launch_at_login` (see the module doc).
///
/// Registering starts the agent immediately (`SuccessfulExit` implies
/// `RunAtLoad`); with the preference off it reads the config and idles out on
/// its own. Re-registering restarts a running agent — wanted: that is how an
/// updated executable replaces the old process under supervision.
///
/// # Errors
///
/// The framework's error description — an unsigned bundle, a missing embedded
/// plist (bare dev binary), or launchd refusing the operation. Never fails
/// off macOS.
pub fn ensure_registered() -> Result<(), String> {
    platform::ensure_registered()
}

/// Open System Settings on the Login Items pane — where the user re-enables a
/// service whose status is [`ServiceStatus::RequiresApproval`].
pub fn open_login_items_settings() {
    platform::open_login_items_settings();
}
